/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lordralex.debugmclauncher;

import com.lordralex.debugmclauncher.panels.IconPanel;
import com.lordralex.debugmclauncher.panels.InformationPanel;
import com.lordralex.debugmclauncher.panels.LoginPanel;
import com.lordralex.debugmclauncher.panels.SystemInformationPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

/**
 *
 * @author Joshua
 */
public class LauncherMain extends javax.swing.JFrame {

    /**
     * Creates new form LauncherMain
     */
    public LauncherMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel1 = new LoginPanel();
        systemInformationPanel1 = new SystemInformationPanel();
        iconPanel1 = new IconPanel();
        informationPanel1 = new InformationPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(0, 0, 0));

        loginPanel1.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        systemInformationPanel1.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        iconPanel1.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        iconPanel1.setPreferredSize(new Dimension(423, 100));

        GroupLayout iconPanel1Layout = new GroupLayout(iconPanel1);
        iconPanel1.setLayout(iconPanel1Layout);
        iconPanel1Layout.setHorizontalGroup(
            iconPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        iconPanel1Layout.setVerticalGroup(
            iconPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        informationPanel1.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        informationPanel1.setPreferredSize(new Dimension(469, 304));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconPanel1, GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(loginPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(informationPanel1, GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(systemInformationPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(informationPanel1, GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(systemInformationPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                    .addComponent(iconPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Map<String, String> map = System.getenv();
                for (String key : map.keySet()) {
                    System.out.println(key + ": " + map.get(key));
                }

                LauncherMain main = new LauncherMain();
                main.setVisible(true);
                main.informationPanel1.getNewsFeed();
                main.systemInformationPanel1.getSystemInfo();
                main.update(main.getGraphics());
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private IconPanel iconPanel1;
    private InformationPanel informationPanel1;
    private LoginPanel loginPanel1;
    private SystemInformationPanel systemInformationPanel1;
    // End of variables declaration//GEN-END:variables
}
